### ISSUE TITLE
show strength and weakness in the overlay

### ISSUE THREAD

**Issue by viktorblack** [ZeroxyDev/MonTally#1]
i would love if it also shows the strength and weakness of the pokemon in the overlay it would be amazing for a beginner pokemon player like me who still have to learn all the types there are

**Comment by ZeroxyDev** [comment]
Thank you for your suggestion! I appreciate your feedback. While the application is primarily designed for capturing Pokémon, I understand that displaying the strengths and weaknesses of Pokémon in the overlay could be incredibly helpful, especially for beginners. Currently, some users also utilize the app for PvP battles to help orient themselves with Pokémon types. While it's not a feature available at the moment, I'll definitely consider implementing something similar in the future. Thanks again for sharing your thoughts!
