### ISSUE TITLE
a request

### ISSUE THREAD

**Issue by kyhftaeonn** [ZeroxyDev/MonTally#3]
its a great project tbh. i like the ui. but the bug like miscount, and sometimes pokemon didnt added its kinda...
so i have a suggestion. now im using different tracker named "BetterFarm" it count, scan pokemon correctly.
maybe if u add some feature like betterfarm it would be great. tbh i like montally more than betterfarm bcs of its UI
so, suggestion from me :
1. Add system save,load, session to save encounter data as csv or anything else
2. Add setup to select specific area for wild pokemon scan

here i addes some screenshot from betterfarm feature for your inspiration (if u didnt know this)
![betterfarm1](https://github.com/ZeroxyDev/MonTally/assets/88365642/f7c4d1ca-66d0-4ec2-ac30-51977b200c56)
![betterfarm2](https://github.com/ZeroxyDev/MonTally/assets/88365642/a54956b9-d107-41a9-8180-845b89154bfc)

**Comment by ZeroxyDev** [comment]
I just uploaded an update, I have greatly improved the detection logic, I have also added an option to be able to select the part of the screen where the names of the pokemon are displayed (you must keep in mind that in the capture area both the individual names and hordes must be visible) 

You can download the latest release here: [https://github.com/ZeroxyDev/MonTally/releases/latest](https://github.com/ZeroxyDev/MonTally/releases/latest)

![capturesettings](https://github.com/user-attachments/assets/f7af36e1-a116-4136-9b22-b7c4c0da4f75)
